name: ✨ Enhancement Request
description: Suggest a new feature or enhancement (LOAD "" CODE your idea!)
title: "[ENHANCEMENT]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ LOAD "" CODE - NEW FEATURE REQUEST
        Got an idea to make this app more speccy-tacular? Let us know!
        
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when... / It would be great if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would love to see a feature that...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or features?
      placeholder: Alternatively, we could...

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: How would this enhancement improve the project?
      placeholder: This would make the app more useful by...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Really need this
        - Critical - Can't use the app without it
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here.
      placeholder: Any additional details, screenshots, or references...
